{% set name = "django-braces" %}
{% set version = "1.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_braces-{{ version }}.tar.gz
  sha256: 3a6fe630d3d91fef0711bfe1088d14af00c245559f79f6298040ed2b2f757337

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.6.6
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - django >=2.2

test:
  imports:
    - braces
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/brack3t/django-braces
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Reusable, generic mixins for Django '
  description: |
    Mixins for Django's class-based views.
  doc_url: https://django-braces.readthedocs.io/en/latest/
  dev_url: https://github.com/brack3t/django-braces

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
    - sannykr
