{% set name = "django-braces" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-braces-{{ version }}.tar.gz
  sha256: f451d08ffc1078d81209a2e17f2219bce20196928853c82405451b18a46875e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=40.6.6
    - wheel
    - pip
  run:
    - python >=3.8
    - django >=2.2

test:
  imports:
    - braces
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brack3t/django-braces
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Reusable, generic mixins for Django '
  description: |
    Mixins for Django's class-based views.
  doc_url: https://django-braces.readthedocs.io/en/latest/
  dev_url: https://github.com/brack3t/django-braces

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
    - sannykr
